# Generated by Django 4.2.4 on 2023-10-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sandshoresmain1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
